//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSolicitudes
    {
        public string Solicitud_ID { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public string TipoSolicitud { get; set; }
        public string Estado { get; set; }
        public string ID_Usuario { get; set; }
    
        public virtual SUsuarios SUsuarios { get; set; }
    }
}
namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUsuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUsuarios()
        {
            this.SSolicitudes = new HashSet<SSolicitudes>();
        }
    
        public string Usuario_ID { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string N_Identificación_Matricula { get; set; }
        public string Rol { get; set; }
        public string Telefono { get; set; }
        public string CorreoElectronico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSolicitudes> SSolicitudes { get; set; }
    }
}
